apiVersion: v1
kind: Namespace
metadata:
  name: nginx-proxy
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-proxy-istio-ingress
  namespace: nginx-proxy
data:
  nginx.conf: |
    worker_processes 1;
    events { worker_connections 1024; }
    stream {
      upstream istio_ingress {
          hash $remote_addr consistent;
          server istio-ingressgateway.istio-system:80;
      }

      server {
          listen *:80;
          proxy_pass istio_ingress;
      }
    }
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-proxy-istio-ingress
  namespace: nginx-proxy
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
          - containerPort: 80
            name: http
            hostPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/
          readOnly: true
        imagePullPolicy: IfNotPresent
      volumes:
      - name: config-volume
        configMap:
          name: nginx-proxy-istio-ingress
